import React, { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ClickAnimation as ClickAnimationType } from "../../types";
import ClickAnimation from "./ClickAnimation";
import miniDiamondImage from "../../assets/diamondsmall.webp";
import diamondImage from "../../assets/diamond.webp";
import { useGameStore } from "../../store/gameStore";

interface ClickerBlockProps {
  clickPower: number;
  multiClickPower: number;
  autoClickerCount: number;
  onClickResource: (power: number) => void;
}

const ClickerBlock: React.FC<ClickerBlockProps> = ({
  clickPower,
  multiClickPower,
  autoClickerCount,
  onClickResource,
}) => {
  const { autoClickerMultiplier } = useGameStore();
  const [clickAnimations, setClickAnimations] = useState<ClickAnimationType[]>(
    []
  );

  // Add effect to show animations when auto clickers generate diamonds
  useEffect(() => {
    // Skip if no auto clickers
    if (autoClickerCount <= 0) return;

    const interval = setInterval(() => {
      // Calculate the actual diamonds generated by auto clickers
      const power = autoClickerCount * autoClickerMultiplier;

      // Generate a random position around the block for the animation
      const blockRadius = 120; // Approximate size of the diamond block
      const angle = Math.random() * 2 * Math.PI; // Random angle
      const distance = blockRadius + Math.random() * 50; // Random distance from center

      // Calculate position based on angle and distance
      const x = Math.cos(angle) * distance + blockRadius / 2;
      const y = Math.sin(angle) * distance + blockRadius / 2;

      // Add a new animation at the calculated position
      const newAnimation = {
        id: Date.now(),
        x,
        y,
        value: power,
      };

      setClickAnimations((prev) => [...prev, newAnimation]);

      // Remove the animation after it completes
      setTimeout(() => {
        setClickAnimations((prev) =>
          prev.filter((anim) => anim.id !== newAnimation.id)
        );
      }, 1000);
    }, 1000); // Same interval as the auto clicker in App.tsx

    return () => clearInterval(interval);
  }, [autoClickerCount, autoClickerMultiplier]);

  const handleClick = (event: React.MouseEvent<HTMLDivElement>) => {
    const power = clickPower * multiClickPower;
    onClickResource(power);

    // Get click position relative to the clicked element
    const rect = event.currentTarget.getBoundingClientRect();
    const x = event.clientX - rect.left;
    const y = event.clientY - rect.top;

    // Add a new animation at the click position
    const newAnimation = {
      id: Date.now(),
      x,
      y,
      value: power,
    };

    setClickAnimations((prev) => [...prev, newAnimation]);

    // Remove the animation after it completes
    setTimeout(() => {
      setClickAnimations((prev) =>
        prev.filter((anim) => anim.id !== newAnimation.id)
      );
    }, 1000);
  };

  return (
    <motion.div
      className="dirt-block"
      whileTap={{ scale: 0.9 }}
      transition={{ type: "spring", stiffness: 400, damping: 17 }}
      onClick={handleClick}
      style={{ position: "relative", overflow: "visible" }}
      onContextMenu={(e) => e.preventDefault()}
    >
      <img
        src={diamondImage}
        alt="Diamond Ore"
        draggable="false"
        onContextMenu={(e) => e.preventDefault()}
      />

      {/* Click animations */}
      <AnimatePresence>
        {clickAnimations.map((anim) => (
          <ClickAnimation
            key={anim.id}
            animation={anim}
            resourceImage={miniDiamondImage}
          />
        ))}
      </AnimatePresence>
    </motion.div>
  );
};

export default ClickerBlock;
