import React from "react";
import { useGameStore } from "../../store/gameStore";
import UpgradeButton from "./UpgradeButton";
import chestImage from "../../assets/chest.jpg";

const UpgradesArea: React.FC = () => {
  const {
    diamondCount,
    clickPower,
    autoClickerCount,
    multiClickPower,
    clickPowerPrice,
    autoClickerPrice,
    multiClickPrice,
    buyClickPower,
    buyAutoClicker,
    buyMultiClick,
    autoClickerMultiplier,
    autoClickerMultiplierPrice,
    buyAutoClickerMultiplier,
  } = useGameStore();

  return (
    <div className="chest-container">
      <div
        className="chest-image"
        style={{
          backgroundImage: `url(${chestImage})`,
        }}
      >
        <div className="chest-content">
          <h2 className="chest-heading">Upgrades</h2>
          <div className="chest-scrollable">
            <div className="upgrade-buttons">
              <UpgradeButton
                title="Click Fortune"
                currentValue={clickPower}
                price={clickPowerPrice}
                disabled={diamondCount < clickPowerPrice}
                onClick={buyClickPower}
                description="Increases the amount of diamonds you get per click"
              />

              <UpgradeButton
                title="Click Efficiency"
                currentValue={multiClickPower}
                price={multiClickPrice}
                disabled={diamondCount < multiClickPrice}
                onClick={buyMultiClick}
                multiplier={true}
                description="Increases the amount of diamonds you get per click by a multiplier"
              />

              <UpgradeButton
                title="Pickaxe"
                currentValue={autoClickerCount}
                price={autoClickerPrice}
                description={`Generates ${
                  autoClickerCount * autoClickerMultiplier
                } diamonds per second`}
                disabled={diamondCount < autoClickerPrice}
                onClick={buyAutoClicker}
              />

              <UpgradeButton
                title="Pickaxe Efficiency"
                currentValue={autoClickerMultiplier}
                price={autoClickerMultiplierPrice}
                disabled={diamondCount < autoClickerMultiplierPrice}
                onClick={buyAutoClickerMultiplier}
                multiplier={true}
                description={`Multiplies diamonds generated by pickaxes`}
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default UpgradesArea;
